-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Thu Aug 17 19:36:10 2023

-- parameterized module component declaration
component main_pll
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : main_pll
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
