function [fitresult, gof] = createFit(y1,a,b,c)
%CREATEFIT(Y1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Sep-2023 13:19:48


%% Fit: 'untitled fit 1'.
y2 = y1-mean(y1)
[xData, yData] = prepareCurveData( [], y2 );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.StartPoint = [a b c];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y1', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'y1', 'Interpreter', 'none' );
grid on


